name: Update Playwright Baseline Snapshots

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_snapshots:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install Browser Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-0 \
          libxss1 \
          libasound2 \
          libx11-xcb1 \
          libnss3 \
          libgconf-2-4 \
          libxcomposite1 \
          libxrandr2 \
          libxi6 \
          libgdk-pixbuf2.0-0 \
          libjpeg-dev \
          fonts-liberation \
          libglib2.0-0 \
          libxss1 \
          libwebp-dev \
          libvpx-dev \
          libicu-dev \ 
          fonts-noto \
          fonts-dejavu \

    - name: Install dependencies
      run: npm install
    
    - name: Install Playwright dependencies
      run: sudo npx playwright install-deps    

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Run Playwright tests and update snapshots
      env:
        DEBUG: playwright:*
      run: npx playwright test --update-snapshots
      continue-on-error: true

    - name: Upload snapshot artifacts
      uses: actions/upload-artifact@v4
      with:
        name: update_snapshot_html_report
        path: '**/html-report/**/*'

    - name: Check for snapshot changes
      id: check_changes
      run: git diff --exit-code || echo "Changes detected"

    - name: Configure Git
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"

    - name: Commit changes if any
      if: steps.check_changes.outcome == 'success'
      run: |
        git add 'snapshots/**/*'  # Adjust this path based on your directory structure
        git commit -m "Update snapshots from CI"
        git push origin main  # Change 'main' to your default branch if different

    - name: No changes to commit
      if: steps.check_changes.outcome != 'success'
      run: echo "No changes detected in snapshots directory."
